@UrlBase = http://localhost:5203

GET {{UrlBase}}/mirrors/
Accept: application/json

###

GET {{UrlBase}}/mirrors/foo
Accept: application/json

###

GET {{UrlBase}}/mirrors/bar
Accept: application/json

###

POST {{UrlBase}}/webhook/reload
Accept: application/json
X-Webhook-Token: {{WebhookToken}}

###

GET {{UrlBase}}/jobs/
Accept: application/json
X-Worker-Token: {{WorkerToken}}

###

POST {{UrlBase}}/jobs/fetch
Accept: application/json
Content-Type: application/json
X-Worker-Token: {{WorkerToken}}

{
  "workerId": "meow"
}

###

PUT {{UrlBase}}/jobs/8ab6d7bd-77d2-4443-b59e-fb88d14931eb
Accept: application/json
Content-Type: application/json
X-Worker-Token: {{WorkerToken}}

{
  "status": 0
}

###

POST {{UrlBase}}/jobs/forceRefresh
Accept: application/json
Content-Type: application/json
X-Worker-Token: {{WorkerToken}}

{
  "mirrorId":  "foo"
}