@UrlBase = http://localhost:5203

GET {{UrlBase}}/mirrors/
Accept: application/json

###

GET {{UrlBase}}/mirrors/foo
Accept: application/json

###

GET {{UrlBase}}/mirrors/bar
Accept: application/json

###

POST {{UrlBase}}/webhook/reload
Accept: application/json
X-Webhook-Token: {{WebhookToken}}

###

GET {{UrlBase}}/jobs/
Accept: application/json
X-Worker-Token: {{WorkerToken}}

###

POST {{UrlBase}}/jobs/fetch
Accept: application/json
Content-Type: application/json
X-Worker-Token: {{WorkerToken}}

{
  "workerId": "meow"
}

###

PUT {{UrlBase}}/jobs/68abebf9-f1a9-40f6-97f1-0d46443f78ac
Accept: application/json
Content-Type: application/json
X-Worker-Token: {{WorkerToken}}

{
  "status": 1
}

###

POST {{UrlBase}}/jobs/forceRefresh
Accept: application/json
Content-Type: application/json
X-Worker-Token: {{WorkerToken}}

{
  "mirrorId":  "foo"
}